version: 0.1
phases:
  install:
    commands:
      - cd /tmp && curl -o terraform.zip https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip && unzip terraform.zip && mv terraform /usr/bin
  build:
    commands:
      - touch ${BUILD_APPNAME}-setup.auto.tfvars
      - echo ${BUILD_TERRAFORM_TFVARS}
      - echo ${BUILD_TERRAFORM_TFVARS_SECURE}
      - echo ${BUILD_TERRAFORM_TFVARS}  > ${BUILD_APPNAME}-setup-global.auto.tfvars
      - echo ${BUILD_TERRAFORM_TFVARS_SECURE} > ${BUILD_APPNAME}-setup-secure.auto.tfvars
      - cat ${BUILD_APPNAME}-setup-global.auto.tfvars
      - cat ${BUILD_APPNAME}-setup-secure.auto.tfvars
      - terraform init -backend-config="bucket=tgr-${BUILD_ENV}-terraform-state" -backend-config="key=tgr-${BUILD_ENV}-${BUILD_APPNAME}-setup"
      - terraform plan
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: '*'