version: 0.1
phases:
   install:
     commands:
       - cd /tmp && curl -o terraform.zip https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip && unzip terraform.zip && mv terraform /usr/bin
   build:
     commands:
       - aws s3 ls tgr-${BUILD_ENV}-terraform-config/${BUILD_APPNAME}-setup
artifacts:
    files:
        - '**/*'
    discard-paths: yes
    base-directory: 'dist*'