version: 0.1
phases:
   install:
     commands:
       - cd /tmp && curl -o terraform.zip https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip && unzip terraform.zip && mv terraform /usr/bin
   build:
     commands:
       - terraform init ${BUILD_ENV}
       - terraform plan -var v_env=${BUILD_ENV} -var v_app=${BUILD_APP} ${BUILD_ENV}
       - terraform apply -var v_env=${BUILD_ENV} -var v_app=${BUILD_APP} -auto-approve ${BUILD_ENV}
      